import { Tanker, Trip, Station } from '@/lib/types'

// Sample data simplified for logistics
export const sampleTankers = [
  { id: 'tnk-001', plate: 'ET-AA-0001', status: 'in_transit', latitude: 9.0120, longitude: 38.7450, currentRoute: 'Bole Station' },
  { id: 'tnk-002', plate: 'ET-AA-0002', status: 'in_transit', latitude: 9.0300, longitude: 38.7600, currentRoute: 'Sarbet Station' },
  { id: 'tnk-003', plate: 'ET-AA-0003', status: 'in_transit', latitude: 9.0550, longitude: 38.7700, currentRoute: 'Nifas Silk Station' },
  { id: 'tnk-004', plate: 'ET-AA-0004', status: 'available', latitude: 9.0400, longitude: 38.7500, currentRoute: 'Base' },
  { id: 'tnk-005', plate: 'ET-AA-0005', status: 'maintenance', latitude: 9.0100, longitude: 38.7800, currentRoute: 'Maintenance Bay' },
]

export const sampleStations = [
  { id: 'stn-001', name: 'TotalEnergies Bole', latitude: 9.0054, longitude: 38.7815 },
  { id: 'stn-002', name: 'TotalEnergies Sarbet', latitude: 9.0218, longitude: 38.7469 },
  { id: 'stn-003', name: 'TotalEnergies Nifas Silk', latitude: 9.0392, longitude: 38.7667 },
  { id: 'stn-004', name: 'TotalEnergies Kazanchis', latitude: 9.0029, longitude: 38.7369 },
  { id: 'stn-005', name: 'TotalEnergies Megenagna', latitude: 9.0538, longitude: 38.7789 },
]

export const sampleDeliveries = [
  { id: 'del-001', tankerId: 'tnk-001', stationId: 'stn-001', fuelType: 'diesel', quantity: 20000, eta: new Date(Date.now() + 30 * 60000).toISOString(), status: 'in_transit' },
  { id: 'del-002', tankerId: 'tnk-002', stationId: 'stn-002', fuelType: 'benzene_95', quantity: 18000, eta: new Date(Date.now() + 45 * 60000).toISOString(), status: 'in_transit' },
  { id: 'del-003', tankerId: 'tnk-003', stationId: 'stn-003', fuelType: 'benzene_97', quantity: 22000, eta: new Date(Date.now() + 20 * 60000).toISOString(), status: 'in_transit' },
]

export const sampleRestockingTimes = [
  { id: 'rst-001', stationId: 'stn-001', fuelType: 'diesel', currentLevel: 15000, capacity: 50000, nextRestockTime: new Date(Date.now() + 1.5 * 3600000).toISOString() },
  { id: 'rst-002', stationId: 'stn-001', fuelType: 'benzene_95', currentLevel: 8000, capacity: 40000, nextRestockTime: new Date(Date.now() + 2 * 3600000).toISOString() },
  { id: 'rst-003', stationId: 'stn-002', fuelType: 'diesel', currentLevel: 22000, capacity: 50000, nextRestockTime: new Date(Date.now() + 3 * 3600000).toISOString() },
  { id: 'rst-004', stationId: 'stn-003', fuelType: 'benzene_97', currentLevel: 12000, capacity: 40000, nextRestockTime: new Date(Date.now() + 45 * 60000).toISOString() },
  { id: 'rst-005', stationId: 'stn-004', fuelType: 'diesel', currentLevel: 5000, capacity: 50000, nextRestockTime: new Date(Date.now() + 1 * 3600000).toISOString() },
]

// TotalEnergies stations in Addis Ababa
export const SAMPLE_STATIONS: Station[] = [
  {
    id: 'stn-001',
    name: 'TotalEnergies Bole',
    address: 'Bole, Addis Ababa',
    latitude: 9.0054,
    longitude: 38.7815,
    phone: '+251-11-123-4567',
    operating_hours: '24/7',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'stn-002',
    name: 'TotalEnergies Sarbet',
    address: 'Sarbet, Addis Ababa',
    latitude: 9.0218,
    longitude: 38.7469,
    phone: '+251-11-234-5678',
    operating_hours: '24/7',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'stn-003',
    name: 'TotalEnergies Nifas Silk',
    address: 'Nifas Silk, Addis Ababa',
    latitude: 9.0392,
    longitude: 38.7667,
    phone: '+251-11-345-6789',
    operating_hours: '24/7',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'stn-004',
    name: 'TotalEnergies Kazanchis',
    address: 'Kazanchis, Addis Ababa',
    latitude: 9.0029,
    longitude: 38.7369,
    phone: '+251-11-456-7890',
    operating_hours: '24/7',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'stn-005',
    name: 'TotalEnergies Megenagna',
    address: 'Megenagna, Addis Ababa',
    latitude: 9.0538,
    longitude: 38.7789,
    phone: '+251-11-567-8901',
    operating_hours: '24/7',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Sample tankers/drivers with real-time locations
export const SAMPLE_TANKERS: Tanker[] = [
  {
    id: 'tnk-001',
    plate_number: 'ET-AA-0001',
    capacity_liters: 30000,
    current_latitude: 9.0120,
    current_longitude: 38.7450,
    status: 'in_transit',
    driver_id: 'driver-001',
    last_location_update: new Date(Date.now() - 5 * 60000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'tnk-002',
    plate_number: 'ET-AA-0002',
    capacity_liters: 25000,
    current_latitude: 9.0300,
    current_longitude: 38.7600,
    status: 'in_transit',
    driver_id: 'driver-002',
    last_location_update: new Date(Date.now() - 3 * 60000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'tnk-003',
    plate_number: 'ET-AA-0003',
    capacity_liters: 30000,
    current_latitude: 9.0550,
    current_longitude: 38.7700,
    status: 'in_transit',
    driver_id: 'driver-003',
    last_location_update: new Date(Date.now() - 8 * 60000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'tnk-004',
    plate_number: 'ET-AA-0004',
    capacity_liters: 25000,
    current_latitude: 9.0400,
    current_longitude: 38.7500,
    status: 'available',
    driver_id: null,
    last_location_update: new Date(Date.now() - 2 * 3600000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'tnk-005',
    plate_number: 'ET-AA-0005',
    capacity_liters: 30000,
    current_latitude: 9.0100,
    current_longitude: 38.7800,
    status: 'maintenance',
    driver_id: null,
    last_location_update: new Date(Date.now() - 24 * 3600000).toISOString(),
    created_at: new Date().toISOString(),
  },
]

// Sample active trips
export const SAMPLE_TRIPS: Trip[] = [
  {
    id: 'trip-001',
    tanker_id: 'tnk-001',
    origin_station_id: null,
    destination_station_id: 'stn-001',
    fuel_type: 'diesel',
    quantity_liters: 20000,
    status: 'in_progress',
    scheduled_departure: new Date(Date.now() - 2 * 3600000).toISOString(),
    actual_departure: new Date(Date.now() - 2 * 3600000).toISOString(),
    estimated_arrival: new Date(Date.now() + 30 * 60000).toISOString(),
    actual_arrival: null,
    created_by: 'user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'trip-002',
    tanker_id: 'tnk-002',
    origin_station_id: null,
    destination_station_id: 'stn-002',
    fuel_type: 'benzene_95',
    quantity_liters: 18000,
    status: 'in_progress',
    scheduled_departure: new Date(Date.now() - 1.5 * 3600000).toISOString(),
    actual_departure: new Date(Date.now() - 1.5 * 3600000).toISOString(),
    estimated_arrival: new Date(Date.now() + 45 * 60000).toISOString(),
    actual_arrival: null,
    created_by: 'user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'trip-003',
    tanker_id: 'tnk-003',
    origin_station_id: null,
    destination_station_id: 'stn-003',
    fuel_type: 'benzene_97',
    quantity_liters: 22000,
    status: 'in_progress',
    scheduled_departure: new Date(Date.now() - 1 * 3600000).toISOString(),
    actual_departure: new Date(Date.now() - 1 * 3600000).toISOString(),
    estimated_arrival: new Date(Date.now() + 20 * 60000).toISOString(),
    actual_arrival: null,
    created_by: 'user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
